name: Hello World
on:
  pull_request:
  workflow_dispatch:
jobs:
  Hello-World-Job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job only runs when manually triggered"
